# Generated by Django 4.2.1 on 2023-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_post_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="publish_date", field=models.DateField(),
        ),
    ]
